### ISSUE TITLE
Closing parenthesis missing from Vfd0 equation for sym_order6b model on the wiki

### ISSUE THREAD

**Issue by rwl** [susantoj/PYPOWER-Dynamics#11]
There is a ) bracket missing from the equation for Vfd0 of the Sauer-Pai model at the bottom of the Machine Models page of the wiki:

https://github.com/susantoj/PYPOWER-Dynamics/wiki/3.4.-Machine-Models#6th-order-synchronous-machine-sauer-pai

![](http://www.openelectrical.org/wiki/images/math/c/9/0/c902804ac44efcdd30098ca382c9ac34.png)

**Comment by susantoj** [comment]
Hi Richard, thanks for picking up this typo. Was also in two other places. All fixed now.
