### ISSUE TITLE
Integer indices

### ISSUE THREAD

**Issue by SanPen** [susantoj/PYPOWER-Dynamics#15]
Hi I have been trying to use pypower dynamics in python3.

So far I have found the following error:
`IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices`

This happens becase the indices are floats instead of integers. The affected function (there might be more) is 

```
def mod_Ybus(Ybus, elements, bus, gen, baseMVA):
    # Add equivalent generator and grid admittances to Ybus matrix
    for element in elements.values():
        Ye = 0
        
        # 4th/6th order machines and converters
        if element.__module__ in ['pydyn.sym_order4', 'pydyn.sym_order6a', 'pydyn.sym_order6b', 'pydyn.vsc_average']:
            i = gen[element.gen_no,0]
            Ye = element.Yg
        
        # External grid
        if element.__module__ == 'pydyn.ext_grid':
            i = gen[element.gen_no,0]
            Ye = 1 / (1j * element.params['Xdp'])
        
        if Ye != 0:
            Ybus[i,i] = Ybus[i,i] + Ye

    # Add equivalent load admittance to Ybus matrix    
    Pl, Ql = bus[:, PD], bus[:, QD]
    for i in range(len(Pl)):
        S_load = (Pl[i] - 1j * Ql[i]) / baseMVA
        y_load = S_load / (bus[i, VM] ** 2)
        Ybus[i,i] = Ybus[i,i] + y_load
    
    return Ybus
```

**Comment by susantoj** [comment]
Hi Santiago, could you send through the model that you are trying to run? I've been using the WinPython 3.3 stack and PYPOWER 4.1.2. There may well be some forward compatibility problems, but I just want to first check if your model works on my stack.

**Comment by SanPen** [comment]
Hi, 

I'm trying to run the default case 9. Nothing new.

The problem is solved by doing ` i = gen[element.gen_no,0].astype(int)` 

In general, every time an index is gathered, it shall be converted to integer so that the newer numpy versions accept it.

**Comment by susantoj** [comment]
Great, thanks for that.

**Comment by liu2bao** [comment]
Same issues.
The index 'source_bus' in run_sim() is recognized as float
