### ISSUE TITLE
Consider switch to BSD license

### ISSUE THREAD

**Issue by rwl** [susantoj/PYPOWER-Dynamics#7]
As of version 5.1, MATPOWER is available under the terms of a 3-clause BSD license and no longer uses the GPLv3.  PYPOWER has been updated and released under the same BSD license.

https://github.com/rwl/PYPOWER/commit/d176356cfa6c1132cbf8d033eb8aa204bf25cf9b

PYPOWER-Dynamics might also be updated to use the BSD license. This would bring it in line with the latest MATPOWER version and with its derived projects.

The switch would allow those unable to work with the GPL license to use PYPOWER-Dynamics and not turn to the older and less capable PyDyn project:

https://github.com/rwl/pydyn

**Comment by susantoj** [comment]
Done!
