### ISSUE TITLE
yi not defined for GAIN equation in controller

### ISSUE THREAD

**Issue by rwl** [susantoj/PYPOWER-Dynamics#8]
The variable `yi` is not defined here:

https://github.com/susantoj/PYPOWER-Dynamics/blob/350f7797ea8a07d08bd0b101b256624af792170f/pydyn/controller.py#L126

The fix looks straightforward.  I'll send a PR soon.

**Comment by susantoj** [comment]
Good pickup, have fixed in latest commit.
